= CONSERVE(1)
:doctype: manpage

== NAME

conserve - robust file backup and restore program.

== SYNOPSIS

    conserve init ARCHIVE
    conserve backup FILE... ARCHIVE
    conserve validate ARCHIVE
    conserve restore ARCHIVE DEST
    conserve printproto FILE

== DESCRIPTION

Conserve is a backup program.

== OPTIONS

*-h*::
    Show help.
    
*-L*::
    Turn off log line prefixes on stderr. By default, a prefix is prepended that includes:
    severity (fatal/error/warning/info); month/day; time; pid; source file line.
    
*-v*::
    Be verbose: show info-level logs on stderr.

*-V*::
    Show the Conserve version number.
    
== EXIT STATUS

0:: 
    Success.

1:: 
    Found differences when comparing: not necessarily a problem if the source filesystem changed since the backup was made.

2:: 
    Encountered problems during operation but continued.

3::
    Stopped due to problems.

4::
    Problem with the command line (bad command or options, etc.)
    
== FILES

Conserve writes log files into `$TMPDIR`. These files have permissions
controlled by the umask, but may contain sensitive filenames.
    
== BUGS

Conserve is immature and should not be used as the only backup mechanism for
valuable data.

Pre-1.0 versions of Conserve do not promise backwards or forwards
compatibility, or that incompatibilities will be cleanly detected and
reported.  In the absence of unplanned bugs, archives can be read by the exact
Conserve version that wrote them.  

From 1.0, no format changes will be made in patchlevel releases, and later
minor releases will be able to read backups made by all previous releases from
1.0 onwards.

Many important features are not yet implemented, including incremental backups
and random access.

== EXAMPLE

    conserve init /backup/my-src
    conserve backup ~/src /backup/my-src
    conserve validate /backup/my-src
    conserve restore /backup/my-src /tmp/restored-src

== AUTHOR

Martin Pool

== SEE ALSO

<http://github.com/sourcefrog/conserve>
