# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='proto/dura.proto',
  package='duralib.proto',
  serialized_pb='\n\x10proto/dura.proto\x12\rduralib.proto\"K\n\rArchiveHeader\x12\r\n\x05magic\x18\x01 \x02(\t\x12\x14\n\x0cread_version\x18\x02 \x02(\x05\x12\x15\n\rwrite_version\x18\x03 \x02(\x05\"\x82\x01\n\tFileIndex\x12\x0c\n\x04path\x18\x01 \x01(\x0c\x12*\n\tfile_type\x18\x02 \x01(\x0e\x32\x17.duralib.proto.FileType\x12\x11\n\tdata_sha1\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x61ta_length\x18\x04 \x01(\x03\x12\x13\n\x0b\x64\x61ta_offset\x18\x05 \x01(\x03\"\\\n\nBlockIndex\x12&\n\x04\x66ile\x18\x01 \x03(\x0b\x32\x18.duralib.proto.FileIndex\x12\x11\n\tdata_sha1\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64\x61ta_length\x18\x03 \x01(\x03*@\n\x08\x46ileType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REGULAR\x10\x01\x12\r\n\tDIRECTORY\x10\x02\x12\x0b\n\x07SYMLINK\x10\x03')

_FILETYPE = descriptor.EnumDescriptor(
  name='FileType',
  full_name='duralib.proto.FileType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REGULAR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DIRECTORY', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SYMLINK', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=339,
  serialized_end=403,
)


UNKNOWN = 0
REGULAR = 1
DIRECTORY = 2
SYMLINK = 3



_ARCHIVEHEADER = descriptor.Descriptor(
  name='ArchiveHeader',
  full_name='duralib.proto.ArchiveHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='magic', full_name='duralib.proto.ArchiveHeader.magic', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='read_version', full_name='duralib.proto.ArchiveHeader.read_version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='write_version', full_name='duralib.proto.ArchiveHeader.write_version', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=110,
)


_FILEINDEX = descriptor.Descriptor(
  name='FileIndex',
  full_name='duralib.proto.FileIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='duralib.proto.FileIndex.path', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='file_type', full_name='duralib.proto.FileIndex.file_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_sha1', full_name='duralib.proto.FileIndex.data_sha1', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_length', full_name='duralib.proto.FileIndex.data_length', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_offset', full_name='duralib.proto.FileIndex.data_offset', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=243,
)


_BLOCKINDEX = descriptor.Descriptor(
  name='BlockIndex',
  full_name='duralib.proto.BlockIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file', full_name='duralib.proto.BlockIndex.file', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_sha1', full_name='duralib.proto.BlockIndex.data_sha1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_length', full_name='duralib.proto.BlockIndex.data_length', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=337,
)

_FILEINDEX.fields_by_name['file_type'].enum_type = _FILETYPE
_BLOCKINDEX.fields_by_name['file'].message_type = _FILEINDEX
DESCRIPTOR.message_types_by_name['ArchiveHeader'] = _ARCHIVEHEADER
DESCRIPTOR.message_types_by_name['FileIndex'] = _FILEINDEX
DESCRIPTOR.message_types_by_name['BlockIndex'] = _BLOCKINDEX

class ArchiveHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARCHIVEHEADER
  
  # @@protoc_insertion_point(class_scope:duralib.proto.ArchiveHeader)

class FileIndex(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILEINDEX
  
  # @@protoc_insertion_point(class_scope:duralib.proto.FileIndex)

class BlockIndex(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOCKINDEX
  
  # @@protoc_insertion_point(class_scope:duralib.proto.BlockIndex)

# @@protoc_insertion_point(module_scope)
